ApiTest/WebApiClient/Controllers/DbController.cs
using Antlr.Runtime.Misc;
using DataFromDb;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace WebApiClient.Controllers
{
    public class DbController : Controller
    {
        string connectionStringArizona = "Server=localhost;Database=Arizona;Integrated Security=true;MultipleActiveResultSets=True;";
        string connectionStringActivePosRead = "Server=localhost;Database=ActivePos_read;Integrated Security=true;";
        string connectionStringActivePosServer = "Server=localhost;Database=ActivePos_server;Integrated Security=true;";
        int topRow = 50;
        int minRow = 1;
        CustomerService customerService = new CustomerService();
        RepetitionService repetitionService = new RepetitionService();

        private DateTime? ConvertToDateTime(object input)
        {
            // If the input is already a DateTime, return it directly
            if (input is DateTime dateTime)
            {
                return dateTime;
            }

            // If the input is a string in the "/Date(...)/" format
            if (input is string sqlDate && !string.IsNullOrEmpty(sqlDate))
            {
                var match = Regex.Match(sqlDate, @"\d+");
                if (match.Success && long.TryParse(match.Value, out long epochMilliseconds))
                {
                    // Convert the epoch milliseconds to DateTime
                    return DateTimeOffset.FromUnixTimeMilliseconds(epochMilliseconds).UtcDateTime;
                }
            }

            // Return null for unsupported formats
            return null;
        }

        // GET: Db
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Institutions()
        {
            var institutions = Institution.GetInstitutions(connectionStringArizona, topRow);

            ViewBag.Institutions = institutions;

            return View();
        }

        // InstitutionsJson
        [HttpGet]
        public JsonResult InstitutionsJson()
        {
            var institutions = Institution.GetInstitutions(connectionStringArizona, topRow);

            // Transform into a list of anonymous objects with a similar structure
            var institutionList = institutions
                .Select(i => new { AdName = i.AdName, ContractNumber = i.ContractNumber, UGuid = i.UGuid })
                .ToList();

            return Json(institutionList, JsonRequestBehavior.AllowGet);
        }


        public ActionResult LimaProducts()
        {
            var products = ProductService.GetLimaProducts(connectionStringArizona);
            ViewBag.Products = products;

            return View();
        }

        // LimaProductsJson
        [HttpGet]
        public JsonResult LimaProductsJson()
        {
            var products = ProductService.GetLimaProducts(connectionStringArizona);

            // Transform into a list of anonymous objects with similar structure
            var productList = products
                .Select(p => new { ItkKey = p.ItkKey, FpPubPrice = p.FpPubPrice, FpMmrPrice = p.FpMmrPrice })
                .ToList();

            return Json(productList, JsonRequestBehavior.AllowGet);
        }


        public ActionResult CustomersInInstitution()
        {
            // Fetch the list of customers in the institution
            List<Customer> customersInInstitution = customerService.GetCustomerInInstitution(connectionStringActivePosRead, topRow);

            //Transform in to a list of tuples, because I have an issue with Objects in the view
            List<Tuple<string, string>> customerList = customersInInstitution
                .Select(c => Tuple.Create(c.FirstName, c.LastName))
                .ToList();

            // Pass the list to the view as the model
            return View(customerList);
        }

        // CustomersInInstitutionJson
        [HttpGet]
        public JsonResult CustomersInInstitutionJson()
        {
            // Fetch the list of customers in the institution
            List<Customer> customersInInstitution = customerService.GetCustomerInInstitution(connectionStringActivePosRead, topRow);

            // Transform into a list of anonymous objects with similar structure
            var customerList = customersInInstitution
                .Select(c => new { FirstName = c.FirstName, LastName = c.LastName })
                .ToList();

            return Json(customerList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CustomersCard()
        {
            List<Customer> customersCard = customerService.GetCustomerCard(connectionStringActivePosRead, topRow);

            //Transform in to a list of tuples, because I have an issue with Objects in the view
            List<Tuple<string, string>> customerList = customersCard
                .Select(c => Tuple.Create(c.FirstName, c.LastName))
                .ToList();

            // Pass the customer to the view as the model
            return View(customerList);
        }

        // CustomersCardJson
        [HttpGet]
        public JsonResult CustomersCardJson()
        {
            List<Customer> customersCard = customerService.GetCustomerCard(connectionStringActivePosRead, topRow);

            // Transform into a list of anonymous objects with similar structure
            var customerList = customersCard
                .Select(c => new { FirstName = c.FirstName, LastName = c.LastName })
                .ToList();

            return Json(customerList, JsonRequestBehavior.AllowGet);
        }


        public ActionResult CustomerEmployee()
        {
            List<Customer> customersEmployee = customerService.GetCustomerEmployee(connectionStringActivePosRead, topRow);

            //Transform in to a list of tuples, because I have an issue with Objects in the view
            List<Tuple<string, string>> customerList = customersEmployee
                .Select(c => Tuple.Create(c.FirstName, c.LastName))
                .ToList();

            // Pass the customer to the view as the model
            return View(customerList);
        }

        // CustomerEmployeeJson
        [HttpGet]
        public JsonResult CustomerEmployeeJson()
        {
            List<Customer> customersEmployee = customerService.GetCustomerEmployee(connectionStringActivePosRead, topRow);

            // Transform into a list of anonymous objects with similar structure
            var customerList = customersEmployee
                .Select(c => new { FirstName = c.FirstName, LastName = c.LastName })
                .ToList();

            return Json(customerList, JsonRequestBehavior.AllowGet);
        }


        public ActionResult CustomerWithAVH()
        {
            List<Customer> customersAvh = customerService.GetCustomerWithAVH(connectionStringActivePosRead, topRow);

            //Transform in to a list of tuples, because I have an issue with Objects in the view
            List<Tuple<string, string>> customerList = customersAvh
                .Select(c => Tuple.Create(c.FirstName, c.LastName))
                .ToList();

            // Pass the customer to the view as the model
            return View(customerList);
        }

        // CustomerWithAVHJson
        [HttpGet]
        public JsonResult CustomerWithAVHJson()
        {
            List<Customer> customersAvh = customerService.GetCustomerWithAVH(connectionStringActivePosRead, topRow);

            // Transform into a list of anonymous objects with similar structure
            var customerList = customersAvh
                .Select(c => new { FirstName = c.FirstName, LastName = c.LastName })
                .ToList();

            return Json(customerList, JsonRequestBehavior.AllowGet);
        }

        //CustomerWithValidInsurance
        public ActionResult CustomerWithValidInsurance()
        {
            List<Customer> customersInsurance = customerService.GetCustomerWithValidInsurance(connectionStringActivePosRead, topRow);

            //Transform in to a list of tuples, because I have an issue with Objects in the view
            List<Tuple<string, string, string, string>> customerList = customersInsurance
                .Select(c => Tuple.Create(c.FirstName, c.LastName, c.AddressId.ToString(), c.InsuranceName))
                .ToList();

            // Pass the customer to the view as the model
            return View(customerList);
        }

        // CustomerWithValidInsuranceJson
        [HttpGet]
        public JsonResult CustomerWithValidInsuranceJson()
        {
            List<Customer> customersInsurance = customerService.GetCustomerWithValidInsurance(connectionStringActivePosRead, topRow);

            // Transform into a list of anonymous objects to match the structure
            var customerList = customersInsurance
                .Select(c => new { FirstName = c.FirstName, LastName = c.LastName, c.AddressId, c.InsuranceName })
                .ToList();

            return Json(customerList, JsonRequestBehavior.AllowGet);
        }

        //CustomerWithValidRepetition
        public ActionResult CustomerWithValidRepetition()
        {
            List<Customer> customersWithRepetition = customerService.GetCustomerWithValidRepetition(connectionStringActivePosRead, topRow);

            //Transform in to a list of tuples, because I have an issue with Objects in the view
            List<Tuple<string, string, string>> customerList = customersWithRepetition
                .Select(c => Tuple.Create(c.FirstName, c.LastName, ConvertToDateTime(c.DateOfBirth)?.ToString("yyyy-MM-dd")))
                .ToList();

            // Pass the customer to the view as the model
            return View(customerList);
        }

        // CustomerWithValidRepetitionJson
        [HttpGet]
        public JsonResult CustomerWithValidRepetitionJson()

ApiTest/WebApiClient/Views/Db/CustomerEmployee.cshtml
@model List<Tuple<string, string>>

<div class="container mt-4">
    <h2 class="mt-4">Customer employee</h2>
    <table class="table table-striped table-bordered">
        <thead class="table-dark">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var customer in Model)
            {
                <tr>
                    <td>@customer.Item1</td>
                    <td>@customer.Item2</td>
                </tr>
            }
        </tbody>
    </table>
</div>

ApiTest/WebApiClient/Views/Db/CvWebShopShippingPharmacy.cshtml
@{
    ViewBag.Title = "CvWebShopShippingPharmacy";
}

<h2>CvWebShopShippingPharmacy Management</h2>

<div>
    <!-- Enable Shipping Pharmacy -->
    <button id="enableShippingPharmacy" class="btn btn-primary btn-md">Enable Shipping Pharmacy</button>

    <!-- Disable Shipping Pharmacy -->
    <button id="disableShippingPharmacy" class="btn btn-primary btn-md">Disable Shipping Pharmacy</button>

    <!-- Get Shipping Pharmacy -->
    <button id="getShippingPharmacy" class="btn btn-primary btn-md">Get Shipping Pharmacy</button>
</div>

<br />

<!-- Display the current value -->
<div>
    <label for="shippingPharmacyValue">Shipping Pharmacy Value:</label>
    <input id="shippingPharmacyValue" class="form-control" readonly />
</div>

@section scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            // Function to set the textbox to "Processing..." before AJAX
            function setProcessing() {
                $('#shippingPharmacyValue').val("Processing...");
            }

            // Enable Shipping Pharmacy
            $('#enableShippingPharmacy').click(function () {
                setProcessing();
                $.ajax({
                    url: '@Url.Action("SetCvWebShopShippingPharmacy", "Db")',
                    type: 'GET',
                    data: { newValue: "1" },
                    success: function (response) {
                        // Parse and display the response value
                        $('#shippingPharmacyValue').val(response.Value || "Error: No value returned");
                    },
                    error: function () {
                        $('#shippingPharmacyValue').val("Failed to enable Shipping Pharmacy");
                    }
                });
            });

            // Disable Shipping Pharmacy
            $('#disableShippingPharmacy').click(function () {
                setProcessing();
                $.ajax({
                    url: '@Url.Action("SetCvWebShopShippingPharmacy", "Db")',
                    type: 'GET',
                    data: { newValue: "0" },
                    success: function (response) {
                        // Parse and display the response value
                        $('#shippingPharmacyValue').val(response.Value || "Error: No value returned");
                    },
                    error: function () {
                        $('#shippingPharmacyValue').val("Failed to disable Shipping Pharmacy");
                    }
                });
            });

            // Get Shipping Pharmacy
            $('#getShippingPharmacy').click(function () {
                setProcessing();
                $.ajax({
                    url: '@Url.Action("GetCvWebShopShippingPharmacy", "Db")',
                    type: 'GET',
                    success: function (response) {
                        // Parse and display the response value
                        $('#shippingPharmacyValue').val(response.Value || "Error: No value returned");
                    },
                    error: function () {
                        $('#shippingPharmacyValue').val("Failed to fetch Shipping Pharmacy value");
                    }
                });
            });
        });
    </script>
}

ApiTest/WebApiClient/Views/Db/ProductInfo.cshtml
@{
    ViewBag.Title = "Product Info";
    Layout = "~/Views/Shared/_Layout.cshtml"; // Ensure Bootstrap layout is used
}

<div class="container mt-4">
    <h2>Product Info</h2>

    <form id="productInfoForm" class="mt-4">
        <div class="row">
            <!-- First Column -->
            <div class="col-md-6">
                <div class="form-group">
                    <label for="searchTerm">Search Term:</label>
                    <input type="text" id="searchTerm" name="searchTerm" class="form-control" placeholder="Enter search term" />
                </div>

                <div class="form-group">
                    <label for="nbRow">Number of Rows:</label>
                    <input type="number" id="nbRow" name="nbRow" class="form-control" value="100" min="1" />
                </div>

                <div class="form-group">
                    <label for="gtinEanCode">GTIN/EAN Code:</label>
                    <input type="text" id="gtinEanCode" name="gtinEanCode" class="form-control" />
                </div>

                <div class="form-group">
                    <label for="pharmacode">Pharmacode:</label>
                    <input type="text" id="pharmacode" name="pharmacode" class="form-control" />
                </div>

                <div class="form-group">
                    <label for="isNarcotic">Is Narcotic:</label>
                    <select id="isNarcotic" name="isNarcotic" class="form-control">
                        <option value="false" selected>false</option>
                        <option value="true">true</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="hasMinMaxQty">Has Min/Max Quantity:</label>
                    <select id="hasMinMaxQty" name="hasMinMaxQty" class="form-control">
                        <option value="false" selected>false</option>
                        <option value="true">true</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="priceEqBigger">Price ≥:</label>
                    <input type="number" id="priceEqBigger" name="priceEqBigger" class="form-control" step="0.01" />
                </div>

                <div class="form-group">
                    <label for="priceEqSmaller">Price ≤:</label>
                    <input type="number" id="priceEqSmaller" name="priceEqSmaller" class="form-control" step="0.01" />
                </div>

                <div class="form-group">
                    <label for="isRequiringSubscription">Requires Prescription:</label>
                    <select id="isRequiringSubscription" name="isRequiringSubscription" class="form-control">
                        <option value="false" selected>false</option>
                        <option value="true">true</option>
                    </select>
                </div>

            </div>

            <!-- Second Column -->
            <div class="col-md-6">
                <div class="form-group">
                    <label for="language">Language:</label>
                    <select id="language" name="language" class="form-control">
                        <option value="1" selected>French</option>
                        <option value="103">German</option>
                        <option value="104">Italian</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="isRequiringFridge">Requires Fridge:</label>
                    <select id="isRequiringFridge" name="isRequiringFridge" class="form-control">
                        <option value="false" selected>false</option>
                        <option value="true">true</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="biosimilar">Biosimilar:</label>
                    <select id="biosimilar" name="biosimilar" class="form-control">
                        <option value="Empty" selected>Empty</option>
                        <option value="1">S</option>
                        <option value="2">R</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="supplierName">Supplier Name:</label>
                    <input type="text" id="supplierName" name="supplierName" class="form-control" />
                </div>

                <div class="form-group">
                    <label for="supplierCode">Supplier Code:</label>
                    <input type="text" id="supplierCode" name="supplierCode" class="form-control" />
                </div>

                <div class="form-group">
                    <label for="itemId">Item ID:</label>
                    <input type="number" id="itemId" name="itemId" class="form-control" />
                </div>

                <div class="form-group">
                    <label for="needGtinEanCode">Need GTIN/EAN Code:</label>
                    <select id="needGtinEanCode" name="needGtinEanCode" class="form-control">
                        <option value="false" selected>false</option>
                        <option value="true">true</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="quantityStockEqBigger">Stock Quantity ≥:</label>
                    <input type="number" id="quantityStockEqBigger" name="quantityStockEqBigger" class="form-control" />
                </div>

                <div class="form-group">
                    <label for="quantityStockEqSmaller">Stock Quantity ≤:</label>
                    <input type="number" id="quantityStockEqSmaller" name="quantityStockEqSmaller" class="form-control" />
                </div>

                
            </div>
        </div>

        <button type="button" id="sendRequest" class="btn btn-primary mt-3">Send</button>
    </form>

    <div class="mt-4">
        <h3>Response</h3>
        <textarea id="jsonResponse" style="width: 100%; max-width: 100%; margin: 0; padding: 0;" rows="25" readonly class="form-control"></textarea>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#sendRequest').click(function () {
            // Disable the button and show "Processing..." in the textarea
            const button = $(this);
            button.prop('disabled', true);
            const responseArea = $('#jsonResponse');
            responseArea.val("Processing...");

            // Gather form data
            const searchTerm = $('#searchTerm').val();
            const nbRow = $('#nbRow').val();
            const language = $('#language').val();
            const gtinEanCode = $('#gtinEanCode').val();
            const pharmacode = $('#pharmacode').val();
            const isRequiringFridge = $('#isRequiringFridge').val();
            const isNarcotic = $('#isNarcotic').val();
            const biosimilar = $('#biosimilar').val();
            const supplierName = $('#supplierName').val();
            const supplierCode = $('#supplierCode').val();
            const itemId = $('#itemId').val();
            const priceEqBigger = $('#priceEqBigger').val();
            const priceEqSmaller = $('#priceEqSmaller').val();
            const quantityStockEqBigger = $('#quantityStockEqBigger').val();
            const quantityStockEqSmaller = $('#quantityStockEqSmaller').val();
            const hasMinMaxQty = $('#hasMinMaxQty').val();
            const needGtinEanCode = $('#needGtinEanCode').val();
            const isRequiringSubscription = $('#isRequiringSubscription').val();

            // Build query string
            let queryString = `searchTerm=${searchTerm}&nbRow=${nbRow}&language=${language}&isRequiringFridge=${isRequiringFridge}&isNarcotic=${isNarcotic}&biosimilar=${biosimilar}&supplierName=${supplierName}&supplierCode=${supplierCode}&itemId=${itemId}&priceEqBigger=${priceEqBigger}&priceEqSmaller=${priceEqSmaller}&quantityStockEqBigger=${quantityStockEqBigger}&quantityStockEqSmaller=${quantityStockEqSmaller}&hasMinMaxQty=${hasMinMaxQty}&needGtinEanCode=${needGtinEanCode}&isRequiringSubscription=${isRequiringSubscription}`;

            // Add gtinEanCode to query string if it's not empty or null
            if (gtinEanCode) {
                queryString += `&gtinEanCode=${gtinEanCode}`;
            }

            // Add pharmacode to query string if it's not empty or null
            if (pharmacode) {
                queryString += `&pharmacode=${pharmacode}`;
            }

            // AJAX request with @Url.Action()
            $.ajax({
                url: '@Url.Action("GetProductsInfo", "Db")?' + queryString,
                method: 'GET',
                timeout: 60000,
                success: function (data) {
                    button.prop('disabled', false);
                    responseArea.val(JSON.stringify(data, null, 2));
                },
                error: function (xhr) {
                    button.prop('disabled', false);
                    responseArea.val(`Error: ${xhr.responseText}`);
                }
            });
        });
    });
</script>

ApiTest/WebApiClient/Views/Db/ProductLinks.cshtml
@{
    ViewBag.Title = "Product Links";
    Layout = "~/Views/Shared/_Layout.cshtml"; // Ensure Bootstrap layout is used
}

<div class="container mt-4">
    <h2>Chained Product (Links)</h2>

    <form id="productLinksForm" class="mt-4">
        <div class="row">
            <!-- First Column -->
            <div class="col-md-6">
                <div class="form-group">
                    <label for="searchTerm">Search Term:</label>
                    <input type="text" id="searchTerm" name="searchTerm" class="form-control" placeholder="Enter search term" />
                </div>

                <div class="form-group">
                    <label for="gtinEanCode">GTIN/EAN Code:</label>
                    <input type="text" id="gtinEanCode" name="gtinEanCode" class="form-control" placeholder="Enter GTIN/EAN Code" />
                </div>

                <div class="form-group">
                    <label for="pharmacode">Pharmacode:</label>
                    <input type="text" id="pharmacode" name="pharmacode" class="form-control" placeholder="Enter Pharmacode" />
                </div>

                <div class="form-group">
                    <label for="nbRow">Number of Rows:</label>
                    <input type="number" id="nbRow" name="nbRow" class="form-control" value="100" min="1" />
                </div>
            </div>

            <!-- Second Column -->
            <div class="col-md-6">
                <div class="form-group">
                    <label for="language">Language:</label>
                    <select id="language" name="language" class="form-control">
                        <option value="1" selected>French</option>
                        <option value="103">German</option>
                        <option value="104">Italian</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="linkType">Link Type:</label>
                    <select id="linkType" name="linkType" class="form-control">
                        <option value="1">Substitution</option>
                        <option value="2">Item With Better Margin</option>
                        <option value="3">Associate Item</option>
                        <option value="4">Item Promotion</option>
                        <option value="5" selected>Replacement</option>
                        <option value="6">Item To Print On Ticket</option>
                        <option value="7">Remark To Print On Ticket</option>
                        <option value="8">Medical Set</option>
                        <option value="9">Migel/Lima</option>
                        <option value="10">Discount</option>
                        <option value="12">Biosimilar</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="needGtinEanCode">Need GTIN/EAN Code:</label>
                    <select id="needGtinEanCode" name="needGtinEanCode" class="form-control">
                        <option value="false" selected>false</option>
                        <option value="true">true</option>
                    </select>
                </div>
            </div>
        </div>

        <button type="button" id="sendRequest" class="btn btn-primary mt-3">Send</button>
    </form>

    <div class="mt-4">
        <h3>Response</h3>
        <textarea id="jsonResponse" style="width: 100%; max-width: 100%; margin: 0; padding: 0;" rows="25" readonly class="form-control"></textarea>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#sendRequest').click(function () {
            // Disable the button and show "Processing..." in the textarea
            const button = $(this);
            button.prop('disabled', true);
            const responseArea = $('#jsonResponse');
            responseArea.val("Processing...");

            // Gather form data
            const searchTerm = $('#searchTerm').val();
            const gtinEanCode = $('#gtinEanCode').val();
            const pharmacode = $('#pharmacode').val();
            const linkType = $('#linkType').val();
            const needGtinEanCode = $('#needGtinEanCode').val();
            const language = $('#language').val();
            const nbRow = $('#nbRow').val();

            // Build query string
            let queryString = `searchTerm=${searchTerm}&linkType=${linkType}&needGtinEanCode=${needGtinEanCode}&language=${language}&nbRow=${nbRow}`;

            // Conditionally add gtinEanCode if not empty
            if (gtinEanCode) {
                queryString += `&gtinEanCode=${gtinEanCode}`;
            }

            // Conditionally add pharmacode if not empty
            if (pharmacode) {
                queryString += `&pharmacode=${pharmacode}`;
            }

            // Debug: Log the full URL to the console
            const fullUrl = '@Url.Action("GetProductLinks", "Db")?' + queryString;
            console.log("Constructed URL: ", fullUrl);

            // Display the URL in the response area (optional)
            responseArea.val(`Debug URL: ${fullUrl}\n\nProcessing...`);

            // AJAX request
            $.ajax({
                url: fullUrl,
                method: 'GET',
                timeout: 60000,
                success: function (data) {
                    // Enable the button and show the response
                    button.prop('disabled', false);
                    responseArea.val(JSON.stringify(data, null, 2));
                },
                error: function (xhr, status, error) {
                    // Enable the button and show the error
                    button.prop('disabled', false);
                    responseArea.val(`Error: ${xhr.responseText}`);
                }
            });
        });
    });
</script>

ApiTest/WebApiClient/Views/Db/Supplier.cshtml
@{
    ViewBag.Title = "SupplierSearch";
}

<h2>Supplier Search</h2>

<div>
    <!-- Search Box -->
    <label for="searchTerm">Enter Search Term:</label>
    <input id="searchTerm" class="form-control" placeholder="Enter a name or term..." />

    <!-- Search Button -->
    <button id="searchButton" class="btn btn-primary btn-md">Search Suppliers</button>
</div>

<br />

<!-- Display the JSON response -->
<div>
    <label for="jsonResponse">JSON Response:</label>
    <textarea id="jsonResponse" class="form-control"  style="width: 100%; max-width: 100%; margin: 0; padding: 0;" rows="25" readonly></textarea>
</div>

@section scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            // Function to set the textarea to "Processing..." before AJAX
            function setProcessing() {
                $('#jsonResponse').val("Processing...");
            }

            // Search Suppliers
            $('#searchButton').click(function () {
                const searchTerm = $('#searchTerm').val(); // Get the value from the search box

                if (!searchTerm) {
                    $('#jsonResponse').val("Please enter a search term.");
                    return;
                }

                setProcessing();
                $.ajax({
                    url: '@Url.Action("GetSuppliersByName", "Db")', // Controller action for supplier search
                    type: 'GET',
                    data: { searchTerm: searchTerm }, // Pass search term to the backend
                    success: function (response) {
                        // Display the JSON response in the textarea
                        $('#jsonResponse').val(JSON.stringify(response, null, 2)); // Pretty-print JSON
                    },
                    error: function () {
                        $('#jsonResponse').val("Failed to fetch supplier data. Please try again.");
                    }
                });
            });
        });
    </script>
}